<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <AssemblyVersion>12.1.0.0</AssemblyVersion>
        <LangVersion>13</LangVersion>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Jellyfin.Controller" Version="12.1.0" />
        <PackageReference Include="Jellyfin.Data" Version="12.1.0" />
        <PackageReference Include="Jellyfin.Database.Implementations" Version="12.1.0" />
        <PackageReference Include="Jellyfin.Extensions" Version="12.1.0" />
        <PackageReference Include="Jellyfin.Model" Version="12.1.0" />
        <PackageReference Include="Jellyfin.Common" Version="12.1.0" />
        <PackageReference Include="Jellyfin.Naming" Version="12.1.0" />
    </ItemGroup>

    <ItemGroup>
        <None Remove="Configuration\configPage.html" />
        <EmbeddedResource Include="Configuration\configPage.html" />
        <None Remove="Web\DeoVRClient.js" />
        <EmbeddedResource Include="Web\DeoVRClient.js" />
        <None Remove="Web\Icon.png" />
        <EmbeddedResource Include="Web\Icon.png" />
    </ItemGroup>
</Project>